Repository jenkinsci/envinject-plugin, pull requests merged in 2019-09, with the labels that each got.

#143 Fix anonymous class serialization warning in EnvInjectComputerListener
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectMasterEnvVarsRetriever.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
Labels: bug

#144 Code cleanup
  src/main/java/hudson/plugins/envfile/EnvFileBuildWrapper.java
  src/main/java/hudson/plugins/setenv/SetEnvBuildWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuilder$1.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectInfo.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfo.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectListener.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPlugin.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration.java
  src/main/java/org/jenkinsci/plugins/envinject/service/BuildCauseRetriever.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
  src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesGetter.java
  src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesVariablesRetriever.java
  src/main/java/org/jenkinsci/plugins/envinject/util/RunHelper.java
  src/main/java/org/jenkinsci/plugins/envinject/util/SortedProperties.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributorTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsEmptyTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfoTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginActionTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectVarListTest.java
Labels: internal

#133 [JENKINS-39403] - Automatically escape single backslashes in the properties loader
  src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
  src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
Labels: bug

#145 [JENKINS-39403] - Add test and simple cleanup
  src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
  src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
Labels: tests
