Repository jenkinsci/envinject-plugin, pull requests merged in 2019-10, with the labels that each got.

#147 Enable incrementals
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: hacktoberfest, internal

#146 Escape paths for network shares
  src/main/java/org/jenkinsci/plugins/envinject/service/PropertiesLoader.java
  src/test/java/org/jenkinsci/plugins/envinject/sevice/PropertiesLoaderTest.java
Labels: enhancement, hacktoberfest

#148 Cleanup deprecated code for non-deprecated equivalent
  src/main/java/hudson/plugins/envfile/EnvFileBuildWrapper.java
  src/main/java/hudson/plugins/setenv/SetEnvBuildWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectBuilder.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectComputerListener.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributor.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectGlobalPasswordWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectInfo.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobProperty.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfo.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectNodeProperty.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPlugin.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginAction.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration.java
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectVarList.java
  src/main/java/org/jenkinsci/plugins/envinject/migration/EnvInjectMigrationListener.java
  src/main/java/org/jenkinsci/plugins/envinject/model/EnvInjectJobPropertyContributor.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectGlobalPasswordRetriever.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectVariableGetter.java
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvironmentVariablesNodeLoader.java
  src/test/java/org/jenkinsci/plugins/envinject/BuildCauseRetrieverTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectActionTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectBuildWrapperTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributorTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectJobPropertyInfoTest.java
  src/test/java/org/jenkinsci/plugins/envinject/GlobalPropertiesTest.java
  src/test/java/org/jenkinsci/plugins/envinject/migration/EnvInjectMigrationBuildWrapperTest.java
  src/test/java/org/jenkinsci/plugins/envinject/sevice/BuildCauseRetrieverTest.java
Labels: hacktoberfest, internal

#150 Move documentation from Wiki to GitHub
  README.md
  docs/CHANGELOG_OLD.md
  docs/images/0e0feead5d341176a406f68395e6f9df8b09a390.png
  docs/images/561833e712b15bbcf3008bf7a34b468608f6c35b.png
  docs/images/a0fe189750e157d60b0a0f6ef844ca9221a1269d.png
  docs/images/bug.svg
  docs/images/ca90953a80d9748b1f558ddcb4e7fb27354dd1b2.png
  docs/images/f6ac7022302083d1e8359babf478bacc1c70f926.png
  docs/images/improvement.svg
  docs/images/rfe.svg
  pom.xml
Labels: documentation
