Repository jenkinsci/envinject-plugin, pull requests merged in 2019-07, with the labels that each got.

#139 [JENKINS-49154] - Resolve job run by BUILD_NUMBER string value instead of the Integer conversion
  src/main/java/org/jenkinsci/plugins/envinject/service/EnvInjectEnvVars.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectEvaluatedGroovyScriptTest.java
Labels: bug

#137 Add DataBoundSetter for EnvInjectPasswordWrapper setters to make them compatible with JobDSL
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPasswordWrapper.java
Labels: enhancement

#140 Enable Release Drafter for the repository
  .github/release-drafter.yml
Labels: internal

#141 Update Jenkins core dependency to 2.138.4 + plugin POM facelift
  pom.xml
Labels: dependencies

#142 Move Changelog to GitHub Releases
  README.md
Labels: documentation

#138 [JENKINS-56449] - Add support for global config via configuration-as-code plugin
  pom.xml
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfiguration.java
  src/test/java/org/jenkinsci/plugins/envinject/EnvInjectPluginConfigurationTest.java
  src/test/resources/org/jenkinsci/plugins/envinject/configuration-as-code.yml
Labels: enhancement
