Repository jenkinsci/envinject-plugin, pull requests merged in 2022-01, with the labels that each got.

#156 chore: Prepare for sunset icon removal from core
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectAction.java
  src/main/resources/util/hetero-list-readonly.jelly
Labels: internal

#153 JENKINS-60559: Log warning when not all environment variables can be injected
  src/main/java/org/jenkinsci/plugins/envinject/EnvInjectEnvVarsContributor.java
Labels: enhancement

#157 chore: Update maintainers metadata in pom.xml
  pom.xml
Labels: internal

#158 Enable Dependabot for the repository
  .github/dependabot.yml
Labels: internal

#167 Use Plugin BOM as a dependencies source + Update to Jenkins 2.303.x
  pom.xml
Labels: dependencies
